package pack;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.RectangleInsets;

/**
 *
 * @author amaln
 */
public class IncomeChartFrame extends javax.swing.JFrame {
    private int userID ;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IncomeChartFrame.class.getName());

    /**
     * Creates new form IncomeChartFrame
     */
    public IncomeChartFrame(int user_id) {
        initComponents();
        setTitle("Monthly Income Report");
        setSize(800, 600);
        setVisible(true);
        setLocationRelativeTo(null);
        this.userID = user_id;
        viewChart();
    }

    private IncomeChartFrame() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
        
    private void viewChart() {
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    try {
        Connection con = DBUtility.getConnection();
        String sql = "SELECT MONTHNAME(date_of_income) as month, SUM(amount) as total " +
                     "FROM income " +
                     "WHERE user_id = ? " +
                     "GROUP BY MONTH(date_of_income), MONTHNAME(date_of_income) " +
                     "ORDER BY MONTH(date_of_income) ASC";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, userID);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            String month = rs.getString("month");
            double amount = rs.getDouble("total");
            dataset.addValue(amount, "Income", month);
        }
        con.close();
    } catch (Exception e) {
        e.printStackTrace();
    }

    // Create chart
    JFreeChart chart = ChartFactory.createLineChart(
        "Monthly Income Trend",
        "Month",
        "Amount ($)",
        dataset,
        PlotOrientation.VERTICAL,
        true, true, false
    );

    // Customize chart appearance
    chart.setBackgroundPaint(new Color(245, 245, 255)); // soft lavender
    chart.getTitle().setFont(new Font("SansSerif", Font.BOLD, 18));

    CategoryPlot plot = chart.getCategoryPlot();
    plot.setBackgroundPaint(new Color(230, 240, 250)); // gentle blue
    plot.setOutlinePaint(Color.WHITE);
    plot.setRangeGridlinePaint(new Color(180, 180, 200)); // light grid lines
    plot.setDomainGridlinesVisible(true);
    plot.setInsets(new RectangleInsets(10, 10, 10, 10));

    // Customize axis fonts
    plot.getDomainAxis().setLabelFont(new Font("SansSerif", Font.PLAIN, 14));
    plot.getRangeAxis().setLabelFont(new Font("SansSerif", Font.PLAIN, 14));
    plot.getDomainAxis().setTickLabelFont(new Font("SansSerif", Font.PLAIN, 12));
    plot.getRangeAxis().setTickLabelFont(new Font("SansSerif", Font.PLAIN, 12));

    // Customize renderer
    LineAndShapeRenderer renderer = new LineAndShapeRenderer();
    renderer.setSeriesPaint(0, new Color(255, 99, 132)); // gentle red
    renderer.setSeriesShapesVisible(0, true);
    renderer.setSeriesStroke(0, new BasicStroke(2.0f));
    plot.setRenderer(renderer);

    // Add chart to panel
    ChartPanel panel = new ChartPanel(chart);
    panel.setMouseWheelEnabled(true);
    setContentPane(panel);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IncomeChartFrame().setVisible(true));
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

