/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack;
import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import javax.swing.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author amaln
 */
public class SavingsChartFrame extends javax.swing.JFrame {
    private int userID;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SavingsChartFrame.class.getName());

    /**
     * Creates new form SavingsChartFrame
     */
    public SavingsChartFrame() {
        initComponents();
    }
     public SavingsChartFrame(int user_id) {
        this.userID = user_id;
        setTitle("Savings Charts");
        setSize(1500, 800);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         setVisible(true);
        JTabbedPane tabbedPane = new JTabbedPane();

        ChartPanel monthlyPanel = new ChartPanel(createMonthlyChart());
        tabbedPane.addTab("Monthly Savings", monthlyPanel);

        // Yearly chart tab
        ChartPanel yearlyPanel = new ChartPanel(createYearlyChart());
        tabbedPane.addTab("Yearly Savings", yearlyPanel);

        setContentPane(tabbedPane);
        setVisible(true);
    }
private JFreeChart createMonthlyChart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        try (Connection con = DBUtility.getConnection()) {
            String sql = "SELECT period_value, amount FROM savings " +
                         "WHERE user_id = ? AND period_type = 'MONTHLY' " +
                         "ORDER BY STR_TO_DATE(period_value, '%M-%Y')";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, userID);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                dataset.addValue(rs.getDouble("amount"), "Savings", rs.getString("period_value"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        JFreeChart chart = ChartFactory.createBarChart(
                "Monthly Savings Report",
                "Month",
                "Savings ($)",
                dataset,
                PlotOrientation.VERTICAL,
                true, true, false
        );
        styleChart(chart);
        return chart;
}
    private JFreeChart createYearlyChart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        try (Connection con = DBUtility.getConnection()) {
            String sql = "SELECT period_value, amount FROM savings " +
                         "WHERE user_id = ? AND period_type = 'YEARLY' " +
                         "ORDER BY period_value";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, userID);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                dataset.addValue(rs.getDouble("amount"), "Savings", rs.getString("period_value"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        JFreeChart chart = ChartFactory.createBarChart(
                "Yearly Savings Report",
                "Year",
                "Savings ($)",
                dataset,
                PlotOrientation.VERTICAL,
                true, true, false
        );
        styleChart(chart);
        return chart;
    }
private void styleChart(JFreeChart chart) {
        chart.getTitle().setFont(new Font("SansSerif", Font.BOLD, 18));
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(new Color(230, 240, 250));
        plot.setRangeGridlinePaint(Color.GRAY);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SavingsChartFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
