/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack;
import javax.swing.table.DefaultTableModel;
import java.sql.*;


/**
 *
 * @author amaln
 */
public class UpdateIncome extends javax.swing.JFrame {
    int userId ;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateIncome.class.getName());

    /**
     * Creates new form UpdateIncome
     */
    public UpdateIncome(int user_id) {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        this.userId = user_id;
        updateIncome();
    }

    private UpdateIncome() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void updateIncome()
    {
    try {
            Connection con = DBUtility.getConnection();
            String sql ="select date_of_income , source,amount,income_id from income where user_id =?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1,userId);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            
            while(rs.next())
            {
                Object [] rowData ={
                    rs.getString("date_of_income"),
                    rs.getString("source"),
                    rs.getString("amount"),
                    rs.getInt("income_id")
                };
                model.addRow(rowData);
                jTable2.setRowHeight(30);
                jTable2.getColumnModel().getColumn(1).setPreferredWidth(200);
            }
            con.close();
        } catch (SQLException ex) {
            System.getLogger(ViewIncome.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }
     void editRows()
     {
         if(jTable2.isEditing())
         {
             jTable2.getCellEditor().stopCellEditing();
         }
         int selectedRow = jTable2.getSelectedRow();
           if (selectedRow != -1) {
             try {
                 Connection con = DBUtility.getConnection();
                 int incomeId = Integer.parseInt(jTable2.getValueAt(selectedRow, 3).toString());
                 String newDate = jTable2.getValueAt(selectedRow, 0).toString();
                 String newSource = jTable2.getValueAt(selectedRow, 1).toString();
                 double newAmount = Double.parseDouble(jTable2.getValueAt(selectedRow, 2).toString());
                 
                 String sql = "UPDATE income SET date_of_income=?, source=?, amount=? WHERE income_id=?";
                 PreparedStatement pst = con.prepareStatement(sql);
                 pst.setString(1, newDate);
                 pst.setString(2, newSource);
                 pst.setDouble(3, newAmount);
                 pst.setInt(4, incomeId);
                 pst.executeUpdate();
                 int flag = 1 ;
                 String message = "              Record updated successfully!!";
                 new MessageFrame(message , flag);
             } catch (SQLException ex) {
                 System.getLogger(UpdateIncome.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
             }
             
} 
        
 else {
    int flag = 0 ;
                String message = "             Please select a row !!";
                new MessageFrame(message , flag);
                return ;
}
     }
    
    
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTable2.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20)); jTable2.getTableHeader().setPreferredSize(new java.awt.Dimension(100, 40));
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(2, 37, 98));
        jButton2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Dashboard");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 180, 50));

        jButton3.setBackground(new java.awt.Color(2, 37, 98));
        jButton3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 180, 50));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Edit & update your income ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 790, 80));

        jTable2.setBackground(new java.awt.Color(51, 51, 51));
        jTable2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Source", "Amount", "Income ID"
            }
        ));
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable2.setShowGrid(true);
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 850, 600));

        jLabel1.setBackground(new java.awt.Color(87, 87, 87));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack/blue.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1960, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(1960, 1080));
        jLabel1.setPreferredSize(new java.awt.Dimension(1960, 1080));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1650, 931));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        editRows();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UpdateIncome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
