/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author amaln
 */
public class YearlySavingsFrame extends javax.swing.JFrame {
    private int userID;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(YearlySavingsFrame.class.getName());

    /**
     * Creates new form MonthlySavingsFrame
     */     
    public YearlySavingsFrame(int user_id) {
        initComponents();
        this.userID = user_id;
        setTitle("Yearly Savings Report");
        setSize(1200, 800);
        setLocationRelativeTo(null);
        setVisible(true);


    }

    private YearlySavingsFrame() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void calculateYearlySavings(){
        try {
            Connection con = DBUtility.getConnection();
            String sql = "INSERT INTO savings (user_id, period_type, period_value, amount) SELECT income_summary.user_id, 'YEARLY', income_summary.period_value, (income_summary.total_income - IFNULL(expense_summary.total_expense, 0)) AS savings FROM (SELECT user_id, YEAR(date_of_income) AS period_value, SUM(amount) AS total_income FROM income WHERE user_id = ? GROUP BY user_id, YEAR(date_of_income)) AS income_summary LEFT JOIN (SELECT user_id, YEAR(date_of_expense) AS period_value, SUM(amount) AS total_expense FROM expense WHERE user_id = ? GROUP BY user_id, YEAR(date_of_expense)) AS expense_summary ON income_summary.user_id = expense_summary.user_id AND income_summary.period_value = expense_summary.period_value ON DUPLICATE KEY UPDATE amount = VALUES(amount)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, userID);
            pst.setInt(2, userID);
            pst.executeUpdate();
            con.close();
        } catch (SQLException ex) {
            System.getLogger(YearlySavingsFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
    private void loadYearlySavingsTable() {
    String[] columnNames = {"Year", "Savings ($)"};
    DefaultTableModel model = new DefaultTableModel(columnNames, 0);

    try (Connection con = DBUtility.getConnection()) {
        String sql = "SELECT period_value, amount FROM savings " +
                     "WHERE user_id = ? AND period_type = 'YEARLY' " +
                     "ORDER BY period_value";

        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, userID);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            String year = rs.getString("period_value");
            double savings = rs.getDouble("amount");
            model.addRow(new Object[]{year, savings});
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    jTable1.setModel(model);  // update your JTable
}
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTable1.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20)); jTable1.getTableHeader().setPreferredSize(new java.awt.Dimension(100, 40));
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Year", "Savings"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setRowHeight(28);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 790, 600));

        jButton1.setBackground(new java.awt.Color(102, 0, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 210, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack/general_bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-920, 0, 2140, 1220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        calculateYearlySavings();
        loadYearlySavingsTable();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new YearlySavingsFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
